### PR TITLE
refactor: Update cert expiry to 10 years

### PR DESCRIPTION
**Pull request by sp98**
Current cert expiry is 356 days. This PR updates the expiry to 3560
days.

Signed-off-by: Santosh Pillai <sapillai@redhat.com>

### CODE REVIEW

**Review by leelavg — APPROVED** [review]
/lgtm

**Review by nbalacha — CHANGES_REQUESTED** [review]
Code is fine. Please modify the commit message to satisfy commitlint requirements.

**Comment by sp98** [comment]
> Code is fine. Please modify the commit message to satisfy commitlint requirements.
done.

**Pull request merged**
