### PR TITLE
build: add nameprefix to the controller manager

### PR DESCRIPTION
**Pull request by iamniting**
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=2047173

### CODE REVIEW

**Review by leelavg — APPROVED** [review]
/lgtm

**Review by nbalacha — COMMENTED** [review]
This works for the controller-manager deployment and pod. Is there any way to do this for the serviceaccount as well?

**Comment by leelavg** [comment]
- I suppose you mean the controller-manager service account
- If that's the case we may need to write a patch file targeting only this serviceAccount and corresponding roles/roleBindings/deployment as I believe we can't set this via kustomize cli
- Needs to be investigated further

**Comment by iamniting** [comment]
> This works for the controller-manager deployment and pod. Is there any way to do this for the serviceaccount as well?

We could do that, But eventually, it will bring much more complexity in the kustomize and makefile because of rbacs and all, I would suggest that we just change the name of the service account to something appropriate so that it won't conflict with something else.

**Review by nbalacha — APPROVED** [review]

**Pull request merged**
