### PR TITLE
OCPVE-187: Add Chad, Jeremy, and Suleyman to the OWNERS

### PR DESCRIPTION
**Pull request by suleymanakbas91**
As a part of ownership transitioning efforts, this PR adds @brandisher, @jerpeter1, and @suleymanakbas91 to the OWNERS.

### CODE REVIEW

**Comment by nbalacha** [comment]
@suleymanakbas91 , please include a  Signed-off-by line in the commit msg.
Suggested commit msg:


chore: add additional owners 

Add Chad, Jeremy, and Suleyman to OWNERS

 Signed-off-by : <xxx>

**Comment by suleymanakbas91** [comment]
> @suleymanakbas91 , please include a Signed-off-by line in the commit msg. Suggested commit msg:
> 
> chore: add additional owners
> 
> Add Chad, Jeremy, and Suleyman to OWNERS
> 
> Signed-off-by :

Sure, I've done it. Is there any particular reason why you're signing off all the commits or is it just for keeping a consistent record of commits?

**Review by nbalacha — APPROVED** [review]

**Comment by suleymanakbas91** [comment]
@nbalacha could you please re-approve? :)

**Pull request merged**
