### PR TITLE
build: always generate fresh bundle

### PR DESCRIPTION
**Pull request by iamniting**
operator-sdk does not delete unnecessary files while generating
a bundle, It just overwrites the required ones and we end up having
resources which is not required anymore. Resolve the same via removing
the bundle directory before generating a bundle.

Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

### CODE REVIEW

**Comment by iamniting** [comment]
Outputs after my testing

```$ oc get csv
NAME                  DISPLAY            VERSION   REPLACES   PHASE
lvm-operator.v0.0.1   ODF LVM Operator   0.0.1                Succeeded
```

```$ oc get pods
NAME                                              READY   STATUS    RESTARTS   AGE
lvm-operator-controller-manager-96465645f-xmdfp   3/3     Running   0          2m26s
topolvm-controller-69ddd6bdff-qx7hz               4/4     Running   0          102s
topolvm-node-jqdms                                4/4     Running   0          102s
vg-manager-lfq9c                                  1/1     Running   0          102s
```

```$ oc get pvc
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
lvm-block-pvc   Bound    pvc-804cefc9-da3d-457d-befb-5d7d7ac911f5   5Gi        RWO            odf-lvm-vg1    10s
lvm-file-pvc    Bound    pvc-a20dafe9-1db7-48b4-8bb5-9951bad5c98b   5Gi        RWO            odf-lvm-vg1    11s
```

**Review by leelavg — APPROVED** [review]
lgtm but why on hold?

**Comment by iamniting** [comment]
> lgtm but why on hold?

I wanted to test this again after cleaning up all resources which OLM does not clean up. and it is working properly.

/hold cancel

**Review by nbalacha — APPROVED** [review]

**Pull request merged**
